### PR TITLE
libtomlc99: Rename blacklist to blocklist

### PR DESCRIPTION
**Pull request by chu11**

### CODE REVIEW

**Comment by grondo** [comment]
Thanks! Want to push this upstream, or has it already been done?

**Comment by chu11** [comment]
upstream as in `flux-core`?  Got a PR for `flux-core` as well.  https://github.com/flux-framework/flux-core/pull/3040#issuecomment-656157803  `tomlc99`'s project doesn't seem to have the term in their repo, I assume they removed it.

**Comment by grondo** [comment]
No, upstream as in the source repo for `libtomlc99`. We didn't write that code and vendored it from somewhere. I assume it is listed in the source or history of commits.

**Comment by grondo** [comment]
> tomlc99's project doesn't seem to have the term in their repo, I assume they removed it.

Ah, then why don't we cherry pick those commits, or update to latest tomlc99?

**Comment by chu11** [comment]
Hmmm. I can't find this test file anywhere including the `tomlc99` history.  From logs:

```
    TAP test replaces upstream test.  It runs the BurntSushi test
    inputs through the parser and checks for expected pass/fail.
    See also: https://github.com/BurntSushi/toml-test
```

@trws did you write this test file?  I can't find it in `toml-test` either.

**Comment by chu11** [comment]
I realized `blocklisted` probably isn't a word, so in one place, `blacklisted` -> `blocklist`

**Comment by grondo** [comment]
Actually, probably @garlick wrote those tests (`git blame` is your friend) or pulled those down from the BurntSushi repo. No upstream changes required. Sorry about the noise!

**Comment by garlick** [comment]
Yeah I'm to blame for the TAP test.  Here's the commit that added it, which explains the BurntSushi tie-in:
```
commit f35927bec7b450e4e4e0c7254fae525e09005212
Author: Jim Garlick <garlick.jim@gmail.com>
Date:   Thu Nov 16 15:25:17 2017 -0800

    libtomlc99: add simple TAP test
    
    The tomlc99 project includes a copy of the general TOML
    test suite: https://github.com/BurntSushi/toml-test
    
    In order to avoid taking on its Golang dependency,
    we simply add a small TAP test that runs all the valid and
    invalid TOML input files from the BurntSushi suite through
    the libtomlc99 parser and ensure that they pass/fail as expected.
    
    A few invalid input files are not handled properly.  Add a
    table of them with the reason for failure so the TAP test
    can skip them and emit the reason for skipping.
```

**Comment by grondo** [comment]
Thanks, @chu11!

**Pull request merged**
