### PR TITLE
ci: remove fedora33 add fedora35 to ci builds

### PR DESCRIPTION
**Pull request by grondo**
Problem: It would be good to test against Fedora 35, but this distro
is missing from the github ci matrix.

Add a build for fedora35 and remove fedora33. Make Fedora 35 the target
for the Address Santizer build, on the presumption that sanitizers are
better in newer releases.

### CODE REVIEW

**Review by garlick — APPROVED** [review]
Sorry, just noticed this! LGTM!

**Comment by grondo** [comment]
Thanks! I forgot about it too!

**Comment by grondo** [comment]
@mergifyio refresh

**Comment by grondo** [comment]
Ah, I missed updating the `.mergify.yml`

**Comment by grondo** [comment]
This probably needs a manual merge now since it touches mergify config.

**Pull request merged**
