### PR TITLE
imp: Allow config file pattern to be overridden for build-tree IMP

### PR DESCRIPTION
**Pull request by grondo**
Posting an early version of this (no tests yet) in case @garlick wants to base casign tests off the result (and give early feedback). Will try to work on a few tests tonight, though I just remembered there is a school function, so perhaps not until tomorrow AM.

Sorry this functionality wasn't here from the start.

### CODE REVIEW

**Comment by grondo** [comment]
Ok, I've pushed some very minor testing updates using the FLUX_IMP_CONFIG_PATTERN support.
While working on this I found some bugs in uses of the imp log functions, so I went ahead and updated those prototypes with printf format attributes and fixed the resulting fallout.

**Comment by garlick** [comment]
Looks good.

I've rebased #48 on this and the only prob was my test under sudo now fails due to missing config file, which sounds right.  I'll just change it to a test_must_fail for now, and when we need a CA as the basis for other tests, we can add an in-tree config file under src/imp, find a place in the tree for ca keys, etc..

Ready to merge this?

**Comment by grondo** [comment]
>  the only prob was my test under sudo now fails due to missing config file, which sounds right. 

Hm, that doesn't sound right to me, the handling of missing config file shouldn't have changed I don't think (but maybe I didn't understand how your test is failing exactly)

**Comment by garlick** [comment]
Fixing my code per offline discussion, and merging this.  Thanks!

**Comment by grondo** [comment]
Thanks!

**Pull request merged**
