### PR TITLE
improve libtomlc99 test coverage

### PR DESCRIPTION
**Pull request by garlick**
This adds unit tests for UTF8 conversion functions in libtomlc99.

As noted in flux-framework/flux-core#1320, these functions lack test coverage.

And actually, `toml_utf8_to_ucs()` appears broken.  I opened an upstream issue on that and commented out its support for multi-byte characters (return error in that case), and changed new unit tests on it to XFAILs.

I also noted there was a couple of test cases upstream that we didn't pick up, and added those.

### CODE REVIEW

**Comment by grondo** [comment]
Excellent, thanks!

**Comment by garlick** [comment]
Looks like I need to exclude toml_tap.c from coverage...

**Comment by grondo** [comment]
> Looks like I need to exclude toml_tap.c from coverage...

Is that file from upstream or developed locally?

**Comment by garlick** [comment]
Local.

**Comment by garlick** [comment]
Actually, I'll just move `toml_tap.c` to `test/toml.c` like the other tests.

**Comment by grondo** [comment]
Nice, ready to merge?

**Comment by garlick** [comment]
Sure!

**Pull request merged**
